Handle IOB that provides PUDC functionality
SymbiFlow/symbiflow-xc-fasm2bels pull request #63
Opened 2021-06-01 22:14 UTC by jgoeders

There is a pin on the FPGA that controls Pull Up behavior of the pins During Configuration (PUDC).  The corresponding IOB will always be in the design, even when not connected.

Current behavior ignores the IOB, which causes an assertion when user logic actually uses it.

This fix leaves the IOB in the design, and then removes it during cleanup if it doesn't connect to user logic.

2021-06-02 13:06 UTC, jgoeders commented
Thanks. I probably forgot to fetch before branching off master, so I'll go update that.

I still have to fix something -- The unused IOB isn't completely removed, as it is still adding a pull up and a top level input.

2021-06-02 15:54 UTC, jgoeders commented
I still have to fix some things, but the license headers failing isn't from this PR.  I'm guessing SymbiFlow/actions/checks@main has changed to now check Verilog files?

2021-06-02 17:46 UTC, mithro commented
@jgoeders - Yes I think that did happen recently.

2021-06-02 22:18 UTC, jgoeders commented
OK, I've fixed the problems of an extra pullup and port being left around from the unused PUDC IOB.  However, we still get this warning:

```
IOSTANDARD setting provided for IOB_X0Y144 do not match its counterpart decoded from the fasm
Requested:
 None
Candidates are:
 LVTTL          
 LVCMOS25       
 TMDS           
 LVCMOS33       
 LVDS           
 SSTL15         
 LVCMOS18       
 LVCMOS15       
 33             
 25             
 LVCMOS12       
 SSTL135
```

This warning occurs because the IOB is only showing up in the design because it is the special PUDC pin; however, the user is not using it with their logic, so there is no IOSTANDARD set.  

The issue is that this IO warning is issued during `process_single_ended_iob`, which occurs *before* `make_routes`.  However, `make_routes` is what we use to determine that this IOB is in fact unused.   So at the time the warning is issued, there's no way to know it is unused.

Some options:
1. Leave the warning there, and let it trigger on cases where the design doesn't use that pin.
1. Mask the warning on the special PUDC IOB (however, if this IOB was actually being used for user logic, and there was an IOSTANDARD mismatch, the warning would be masked.)  Or we could just mask it in the case of the PUDC pin and IOSTANDARD  is None.  
1. Otherwise to **properly** fix it, we would need to move this warning code to post-route.  I can try and do that if it's preferred.  I don't know the code well enough to know if there are other implications to restructuring it this way.

2021-06-08 18:42 UTC, mithro commented
@jaromharris - You will want to create a separate pull request for the verilog header files fixes.

2021-06-08 21:20 UTC, jgoeders commented
> Otherwise to properly fix it, we would need to move this warning code to post-route. I can try and do that if it's preferred. I don't know the code well enough to know if there are other implications to restructuring it this way.

I've moved the IBUF IOSTANDARD processing to after make_routes and port cleanup.  This removes the lingering warning, but required a bit more reorganization.

For consistency, we might consider moving the OBUF IOSTANDARD processing to the same location, although currently there is no **need** for it to move.  Let me know if you want me to make that change as well.

2021-06-28 19:03 UTC, jgoeders commented
@mkurc-ant I think this is ready to be merged when you have a chance to look at it.

2021-06-29 07:10 UTC, mkurc-ant requested changes
The changes looks good and the current tests are passing. What I'd like you to do is to add a test case with a design that uses the PUDC site as an input.

You can create a simplistic design, then manually run it through `fasm2bels` to get the golden reference output (which in this case has to be manually examined for correctness). That's my only request, the rest looks fine.

2021-07-07 17:38 UTC, TheDHCreator commented
@mkurc-ant Jeff Goeders assigned me to do the PUDC test case that I just merged. Let me know when you've taken a look at it.

2021-07-08 16:17 UTC, mkurc-ant commented
@TheDHCreator I see that the PUDC test fails after merging in the master branch. Unfortunately I cannot immediately see why is that.

2021-07-08 16:43 UTC, TheDHCreator commented
@mkurc-ant I believe that right when I was merging the test_data/pudc branch, the carry4 branch from another pull request got merged into master. I think I just need to rebase but I am not sure how to do that.

2021-07-08 16:53 UTC, mkurc-ant commented
@TheDHCreator Yeah, It is better to do rebases instead of merging master into a branch. Please try that. Let's see what the CI will tell then.

2021-07-08 17:43 UTC, TheDHCreator commented
I have not yet rebased correctly. Still working on doing it right.

2021-07-09 17:49 UTC, TheDHCreator commented
@mkurc-ant The rebase has been performed properly, the golden files from the carry4 branch that was merged a few days ago had to be reconfigured and I had too many new lines in the pudc golden files. All of those have now been corrected and Workflow #69 on the BYU Fasm2bels repo has both of the CI tests passing. Please let me know when you've taken a look.

2021-07-12 07:59 UTC, mkurc-ant commented
@TheDHCreator The CI has passed, I'm merging this PR. Thanks for the contribution!

2021-07-12 07:59 UTC, merged