Equivalence checking
SymbiFlow/symbiflow-xc-fasm2bels pull request #68
Opened 2021-07-20 00:19 UTC by jaromharris

This PR has a new unit test that takes ideas from what we have been doing on BYU's FPGA Assurance Tool --> https://github.com/byuccl/bfasst specifically equivalence checking using Yosys. The test generates a reversed verilog netlist from a .bit and .xdc file using fasm2bels, and then compares it with a golden Vivado generated verilog netlist that produced the .bit file. 

The design that it is currently testing is a simple 32 bit adder-- it doesn't test anything specific, but I wanted to include a simple design as an example of how this would work. (And also the Yosys commands in tests/test_equivalence.py run into errors when running more complicated designs). 

One last thing to note is that building Yosys takes quite a while (~30 minutes) which may not be ideal for CI tests. Do you have any suggestions for speeding this up?

2021-07-20 19:39 UTC, mithro commented
@kgugala -- Can you route this to the right people to look at?

2021-07-20 20:02 UTC, mithro commented
(FYI - @QuantamHD)

2021-07-21 20:29 UTC, mithro commented
(FYI - @hzeller -- Something like this could be useful in the frontend side too..)

2021-07-22 12:39 UTC, kgugala commented
hi @jaromharris, thanks for the PR.

> One last thing to note is that building Yosys takes quite a while (~30 minutes) which may not be ideal for CI tests. Do you have any suggestions for speeding this up?

We can use Yosys from conda here. Also it may be a good idea to freeze Yosys version - otherwise we may get red CI just because Yosys changed.

2021-07-29 16:45 UTC, jaromharris commented
@kgugala Hi, thanks for reviewing this. How would I go about building Yosys from conda? @mkurc-ant mentioned in our meeting that [symbiflow-arch-defs](https://github.com/SymbiFlow/symbiflow-arch-defs) builds Yosys from conda. I've tried to replicate what is done there, but I'm not having much success. Here are some specific questions:

Where do I install the prerequisite packages? 
Is it necessary to clone Yosys as a submodule?
Should I be using the [make-env](https://github.com/SymbiFlow/make-env] repo to make the conda environment?
In what way does building Yosys from conda speed up the build process?

Thanks

2021-08-06 09:36 UTC, acomodi commented
Hi @jaromharris, I think that with ccache in the GH action CI the yosys build step is faster, and I see that it took ~2m to build yosys.

The advantage though in using yosys from conda is that the yosys package is already pre-built and we would only need to grab those.
To use conda, you can follow [these instruction](https://github.com/SymbiFlow/make-env#option-1a----git-submodules) to add make-env as a submodule. Thank you would need an environment file similar to [this one](https://github.com/SymbiFlow/fpga-interchange-tests/blob/master/environment.yml) with the yosys package only, and the requirements.txt files.

The yosys conda packages can be found [here](https://anaconda.org/LiteX-Hub/yosys/files). You should grab the latest one that has the `main` label assigned.

This would require also some adjustments to the Makefile as done [here](https://github.com/SymbiFlow/fpga-interchange-tests/blob/fe9b3ffac7bb9038c51f26c3864931a0b68b5a14/Makefile#L10-L11).

After setting everything up, by running `make env`, the environment will be generated using the packages specified in the environment file, and all the dependencies downloaded. Once the environment is created, you can enter it by running `make enter`, and yosys will be available.

2021-09-03 08:31 UTC, acomodi requested changes
LGTM, one thing that would be necessary though is to squash the commits with the merge conflicts: https://github.com/SymbiFlow/symbiflow-xc-fasm2bels/pull/68/commits/c758b2482762852951d2cdeb9e36bb02dc46b66f and https://github.com/SymbiFlow/symbiflow-xc-fasm2bels/pull/68/commits/df86b0ce11a040ff36b8680bb2b702a70522826e

2021-09-06 08:12 UTC, acomodi requested changes
You might have accidentally removed the addition of the make-env submodule while squashing the commits, causing the CI failure:

```
Run export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
Makefile:19: third_party/make-env/conda.mk: No such file or directory
make: *** No rule to make target 'third_party/make-env/conda.mk'.  Stop.
Error: Process completed with exit code 2.
```

2021-09-07 15:54 UTC, jaromharris commented
Thanks, should be good to go now

2021-09-14 10:20 UTC, acomodi approved these changes
@jaromharris thanks for the changes, LGTM! merging

2021-09-14 10:21 UTC, merged